import { AugmentDefSchema, type AugmentDef } from '@reforged/schema';

/**
 * 10 augments per tier (bronze/silver/gold), picked 1-of-3 every 2 rounds —
 * see plan decision #7 for the tier-by-pick-index rule. Effects are applied
 * team-wide at combat start by combatOrchestrator (see engine.ts's
 * `augmentEffects` input) — never the self-only buff_attack/buff_attack_speed
 * kinds, since an augment has no single "caster" to exclude from a team buff.
 *
 * Several are tag-locked (`tagFilter`) so picking a run of them builds toward
 * a specialization instead of every augment just being a flat number-go-up;
 * a few (`grantUnitId`) hand you a specific unit outright on top of their
 * combat effect.
 */
const raw: AugmentDef[] = [
  // --- BRONZE ---
  {
    id: 'bronze-steady-hands',
    name: 'Pewna Ręka',
    tier: 'bronze',
    icon: '⚔️',
    description: 'Wszystkie jednostki zadają +5% obrażeń.',
    effect: { kind: 'buff_team_attack', percent: 5 },
  },
  {
    id: 'bronze-quick-step',
    name: 'Szybki Krok',
    tier: 'bronze',
    icon: '👟',
    description: 'Wszystkie jednostki atakują o 5% szybciej.',
    effect: { kind: 'buff_team_attack_speed', percent: 5 },
  },
  {
    id: 'bronze-reinforced-hull',
    name: 'Wzmocniony Kadłub',
    tier: 'bronze',
    icon: '🧱',
    description: 'Drużyna zaczyna każdą walkę z tarczą 30.',
    effect: { kind: 'shield_own_pool', amount: 30 },
  },
  {
    id: 'bronze-cursed-blade',
    name: 'Przeklęte Ostrze',
    tier: 'bronze',
    icon: '☠️',
    description: 'Zatruwa wroga na 3 obrażeń na sekundę przez całą walkę.',
    effect: { kind: 'poison_enemy_pool', damagePerSec: 3 },
  },
  {
    id: 'bronze-clumsy-feet',
    name: 'Niezdarne Nogi',
    tier: 'bronze',
    icon: '🐌',
    description: 'Spowalnia wroga — jego jednostki atakują o 8% wolniej.',
    effect: { kind: 'slow_enemy_team_attack_speed', percent: 8 },
  },
  {
    id: 'bronze-rust',
    name: 'Rdza',
    tier: 'bronze',
    icon: '🦠',
    description: 'Osłabia wroga — jego jednostki zadają o 8% mniej obrażeń.',
    effect: { kind: 'weaken_enemy_team_attack', percent: 8 },
  },
  {
    id: 'bronze-field-rations',
    name: 'Suchy Prowiant',
    tier: 'bronze',
    icon: '🍞',
    description: 'Drużyna leczy 20 HP na starcie każdej walki.',
    effect: { kind: 'heal_own_pool', amount: 20 },
  },
  {
    id: 'bronze-figlarz-spirit',
    name: 'Duch Figlarza',
    tier: 'bronze',
    icon: '🃏',
    description: 'Jednostki z tagiem "figlarz" atakują o 12% szybciej.',
    effect: { kind: 'buff_team_attack_speed', percent: 12 },
    tagFilter: ['figlarz'],
  },
  {
    id: 'bronze-szachista-focus',
    name: 'Skupienie Szachisty',
    tier: 'bronze',
    icon: '♟️',
    description: 'Jednostki z tagiem "szachista" zadają +12% obrażeń.',
    effect: { kind: 'buff_team_attack', percent: 12 },
    tagFilter: ['szachista'],
  },
  {
    id: 'bronze-recruit',
    name: 'Świeży Rekrut',
    tier: 'bronze',
    icon: '🎫',
    description: 'Natychmiast dołącza SkibidiKubuś do ławki. Wszystkie jednostki zadają +3% obrażeń.',
    effect: { kind: 'buff_team_attack', percent: 3 },
    grantUnitId: 'skibidi_kubus',
  },

  // --- SILVER ---
  {
    id: 'silver-adrenaline',
    name: 'Adrenalina',
    tier: 'silver',
    icon: '💉',
    description: 'Wszystkie jednostki zadają +12% obrażeń.',
    effect: { kind: 'buff_team_attack', percent: 12 },
  },
  {
    id: 'silver-overclock',
    name: 'Przetaktowanie',
    tier: 'silver',
    icon: '⏩',
    description: 'Wszystkie jednostki atakują o 12% szybciej.',
    effect: { kind: 'buff_team_attack_speed', percent: 12 },
  },
  {
    id: 'silver-battle-medicine',
    name: 'Medycyna Polowa',
    tier: 'silver',
    icon: '💊',
    description: 'Drużyna leczy 40 HP na starcie każdej walki.',
    effect: { kind: 'heal_own_pool', amount: 40 },
  },
  {
    id: 'silver-toxic-cloud',
    name: 'Toksyczna Chmura',
    tier: 'silver',
    icon: '☣️',
    description: 'Zatruwa wroga na 8 obrażeń na sekundę przez całą walkę.',
    effect: { kind: 'poison_enemy_pool', damagePerSec: 8 },
  },
  {
    id: 'silver-quagmire',
    name: 'Bagnisko',
    tier: 'silver',
    icon: '🥾',
    description: 'Spowalnia wroga — jego jednostki atakują o 15% wolniej.',
    effect: { kind: 'slow_enemy_team_attack_speed', percent: 15 },
  },
  {
    id: 'silver-corrosion',
    name: 'Korozja',
    tier: 'silver',
    icon: '🧪',
    description: 'Osłabia wroga — jego jednostki zadają o 15% mniej obrażeń.',
    effect: { kind: 'weaken_enemy_team_attack', percent: 15 },
  },
  {
    id: 'silver-decaying-ward',
    name: 'Zanikająca Osłona',
    tier: 'silver',
    icon: '🔮',
    description: 'Drużyna zaczyna walkę z tarczą 80, która zanika o 20% co sekundę.',
    effect: { kind: 'shield_own_pool', amount: 80, decayPercentPerSec: 20 },
  },
  {
    id: 'silver-konfident-network',
    name: 'Sieć Konfidenta',
    tier: 'silver',
    icon: '🤝',
    description: 'Jednostki z tagiem "konfident" atakują o 18% szybciej.',
    effect: { kind: 'buff_team_attack_speed', percent: 18 },
    tagFilter: ['konfident'],
  },
  {
    id: 'silver-starociota-wisdom',
    name: 'Mądrość Starociota',
    tier: 'silver',
    icon: '📜',
    description: 'Jednostki z tagiem "starociota" zadają +18% obrażeń.',
    effect: { kind: 'buff_team_attack', percent: 18 },
    tagFilter: ['starociota'],
  },
  {
    id: 'silver-veteran-recruit',
    name: 'Weteran',
    tier: 'silver',
    icon: '🎖️',
    description: 'Natychmiast dołącza Sofronow do ławki. Drużyna leczy 15 HP na starcie walki.',
    effect: { kind: 'heal_own_pool', amount: 15 },
    grantUnitId: 'sofronow',
  },

  // --- GOLD ---
  {
    id: 'gold-berserk',
    name: 'Szał Bojowy',
    tier: 'gold',
    icon: '🪓',
    description: 'Wszystkie jednostki zadają +25% obrażeń.',
    effect: { kind: 'buff_team_attack', percent: 25 },
  },
  {
    id: 'gold-hyperspeed',
    name: 'Nadprędkość',
    tier: 'gold',
    icon: '🌀',
    description: 'Wszystkie jednostki atakują o 25% szybciej.',
    effect: { kind: 'buff_team_attack_speed', percent: 25 },
  },
  {
    id: 'gold-aegis',
    name: 'Egida',
    tier: 'gold',
    icon: '🛡️',
    description: 'Drużyna zaczyna każdą walkę z tarczą 100.',
    effect: { kind: 'shield_own_pool', amount: 100 },
  },
  {
    id: 'gold-plague',
    name: 'Zaraza',
    tier: 'gold',
    icon: '🦠',
    description: 'Zatruwa wroga na 15 obrażeń na sekundę przez całą walkę.',
    effect: { kind: 'poison_enemy_pool', damagePerSec: 15 },
  },
  {
    id: 'gold-frozen-ground',
    name: 'Zamarznięty Grunt',
    tier: 'gold',
    icon: '❄️',
    description: 'Spowalnia wroga — jego jednostki atakują o 25% wolniej.',
    effect: { kind: 'slow_enemy_team_attack_speed', percent: 25 },
  },
  {
    id: 'gold-sunder',
    name: 'Rozłam',
    tier: 'gold',
    icon: '💥',
    description: 'Osłabia wroga — jego jednostki zadają o 25% mniej obrażeń.',
    effect: { kind: 'weaken_enemy_team_attack', percent: 25 },
  },
  {
    id: 'gold-phoenix-ward',
    name: 'Osłona Feniksa',
    tier: 'gold',
    icon: '🔥',
    description: 'Drużyna zaczyna walkę z tarczą 150, która zanika o 10% co sekundę.',
    effect: { kind: 'shield_own_pool', amount: 150, decayPercentPerSec: 10 },
  },
  {
    id: 'gold-srebrna-gwardia-bastion',
    name: 'Bastion Srebrnej Gwardii',
    tier: 'gold',
    icon: '🏰',
    description: 'Jednostki z tagiem "srebrna gwardia" atakują o 30% szybciej.',
    effect: { kind: 'buff_team_attack_speed', percent: 30 },
    tagFilter: ['srebrna-gwardia'],
  },
  {
    id: 'gold-nowociota-surge',
    name: 'Zryw Nowociota',
    tier: 'gold',
    icon: '⚡',
    description: 'Jednostki z tagiem "nowociota" zadają +30% obrażeń.',
    effect: { kind: 'buff_team_attack', percent: 30 },
    tagFilter: ['nowociota'],
  },
  {
    id: 'gold-champion-recruit',
    name: 'Mistrz Areny',
    tier: 'gold',
    icon: '👑',
    description: 'Natychmiast dołącza Fiko do ławki. Wszystkie jednostki zadają +10% obrażeń.',
    effect: { kind: 'buff_team_attack', percent: 10 },
    grantUnitId: 'fiko',
  },
];

export const augmentDefs: AugmentDef[] = raw.map((augment) => AugmentDefSchema.parse(augment));
